name: Publish Python package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      run: python3.9 -m pip install poetry

    - name: Create .env
      run: |
        echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
        echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env

    - name: Install dependencies
      run: python3.9 -m poetry install

    - name: Run tests
      run: python3.9 -m poetry run pytest

    - name: Configure PyPI token
      run: python3.9 -m poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Build and publish to PyPI
      run: python3.9 -m poetry publish --build
